name: Build Vial Firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        uses: qmk/qmk-action@v5
        with:
          palette: false
          keyboard: crkbd/rev1
          keymap: vial

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: corne-vial-firmware
          path: |
            *.hex
            *.uf2
            *.bin
