name: Build Vial Firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          qmk compile -kb crkbd/rev1 -km vial
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: corne-vial-firmware
          path: |
            *.hex
            *.uf2
            *.bin
